### ISSUE TITLE
Nuget package is unsigned

### ISSUE THREAD

**Issue by Mostafa-Armandi** [Yortw/Yort.Ntp#17]
Please sign the .nuget package so that to be reference from within any signed assembly.

**Comment by Yortw** [comment]
Hi,

Unfortunately strong naming the assemblies causes me issues in my own projects. Some libraries create secondary packages that are signed. However, aside from the extra maintenance burden involved in setting that up and maintaining it, I've read that's not ideal because it means other library authors then have to decide whether to use the strong or weak named package, or produce two packages themselves.

Have you considered using one of the following solutions to automatically strong name the assembly you reference during your build process? This would mean library authors like myself can continue shipping weakly named packages and you can still use them in the few situations that still require strong naming.

[https://github.com/dsplaisted/strongnamer](https://github.com/dsplaisted/strongnamer)
[https://brutaldev.com/post/net-assembly-strong-name-signer](https://brutaldev.com/post/net-assembly-strong-name-signer)
