### ISSUE TITLE
Get a problem trying to build .net core

### ISSUE THREAD

**Issue by apawsey** [Yortw/Yort.Ntp#3]
Just gone back to some stuff I was working on, to update to RC2 (core stuff).  I updated all the packages and things, including this one to 1.0.7, and now my build... he not happy.

I'm fiddling with the project.json/.lock to try and work out why it's doing this, but I thought I'd let you know in the mean time, in case you have the magic answer :)

C:\TFSDefault\PayteqCore\src\Payteq.Core\Services\Licensing\Validation\LicenseValidationExtensions.cs(65,13): error CS0433: The type 'NtpClient' exists in both 'Yort.Ntp.Net45, Version=1.0.0.6, Culture=neutral, PublicKeyToken=null' and 'Yort.Ntp, Version=1.0.0.7, Culture=neutral, PublicKeyToken=null'
C:\TFSDefault\PayteqCore\src\Payteq.Core\Services\Licensing\Validation\LicenseValidationExtensions.cs(65,39): error CS0433: The type 'NtpClient' exists in both 'Yort.Ntp.Net45, Version=1.0.0.6, Culture=neutral, PublicKeyToken=null' and 'Yort.Ntp, Version=1.0.0.7, Culture=neutral, PublicKeyToken=null'

**Comment by Yortw** [comment]
To be honest I didn't even know it worked in .Net core, I've never tried (waiting for .net core to stabilize before I invest time in it).

I don't know exactly what your issue is (having not seen it or tried it from a .net core project), but it looks like multiple references.

You should only have one reference, to one DLL. It looks like either you've got reference to 1.0.6 &1.0.7 or possibly you have the portable and .net FX assemblies referenced.

Either way, I believe you only want to reference the 1.0.7 net45 assembly. Getting rid of the other references should help.

It could be my fault, as I _think_ I screwed up the assemblies in the early releases and they had different names, which I fixed in 1.0.7 by renaming them. Didn't cause me any grief upgrading my projects, but perhaps project.json/nuget 3 etc works differently and didn't cope with the rename?

**Comment by Yortw** [comment]
Hi, did you have any luck getting it to work?

**Comment by groege** [comment]
Hi!
Any news on this? Would be nice to have a library instead of having to write my own ;)

**Comment by Yortw** [comment]
I've just published an updated package (version 11) that contains a .Net Standard 1.3 assembly. This should work on Net Core or any Net Standard project targeting 1.3 or later. I tested it briefly in a Net Core console app, and it worked for me, but that is the extent of my testing so far. Latest Nuget package should be available after the next reindex, so within 15 mins.
